import { access, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { describe, expect, it } from "vitest";

import { InstructionService } from "../packages/instructions/src/index.js";

describe("InstructionService", () => {
  it("previews repo-aware Copilot instructions from repo analysis", async () => {
    const repoRoot = await createRepo({
      "package.json": JSON.stringify({
        dependencies: { react: "^18.0.0" },
        scripts: {
          build: "vite build",
          test: "vitest run",
          lint: "eslint .",
          format: "prettier --check ."
        }
      }),
      "src/App.tsx": "export function App() { return <main />; }"
    });

    const preview = await new InstructionService().preview({ startPath: repoRoot });

    expect(preview.outputPath).toBe(
      path.join(repoRoot, ".github/copilot-instructions.md")
    );
    expect(preview.markdown).toContain("## Repo Architecture Summary");
    expect(preview.markdown).toContain("Generated by Copilot Architect at");
    expect(preview.markdown).toContain("Source repo-map schema:");
    expect(preview.markdown).toContain("## Detected Languages");
    expect(preview.markdown).toContain("TypeScript");
    expect(preview.markdown).toContain("React");
    expect(preview.markdown).toContain("npm run build");
    expect(preview.skills.map((skill) => skill.id)).toEqual([
      "feature-planning",
      "repo-analysis",
      "validation",
      "code-review",
      "debugging"
    ]);
    expect(preview.prompts.map((prompt) => prompt.id)).toEqual([
      "copilot-architect-plan",
      "copilot-architect-implement",
      "copilot-architect-review",
      "copilot-architect-debug"
    ]);
  });

  it("generates instructions and skills with backups and preserved user content", async () => {
    const repoRoot = await createRepo({
      "package.json": JSON.stringify({ scripts: { test: "vitest run" } }),
      "src/invoice.ts": "export const invoice = true;"
    });
    const instructionPath = path.join(repoRoot, ".github/copilot-instructions.md");

    await mkdir(path.dirname(instructionPath), { recursive: true });
    await writeFile(instructionPath, "## Team Notes\n\nKeep invoices boring.", "utf8");

    const result = await new InstructionService().generate({ startPath: repoRoot });
    const generated = await readFile(instructionPath, "utf8");

    expect(result.status).toBe("updated");
    expect(result.backupPath).toBeDefined();
    expect(result.preservedUserContent).toBe(true);
    expect(result.skills).toHaveLength(5);
    expect(result.prompts).toHaveLength(4);
    expect(generated).toContain("## Preserved User Notes");
    expect(generated).toContain("Keep invoices boring.");
    await access(result.backupPath ?? "");
    await access(path.join(repoRoot, ".github/skills/validation/SKILL.md"));
    await access(
      path.join(repoRoot, ".github/prompts/copilot-architect-plan.prompt.md")
    );
  });

  it("validates instructions and catches missing skills", async () => {
    const repoRoot = await createRepo({
      "package.json": JSON.stringify({ name: "instructions-validation" })
    });
    const service = new InstructionService();

    const missing = await service.validate({ startPath: repoRoot });
    await service.generate({ startPath: repoRoot });
    const valid = await service.validate({ startPath: repoRoot });

    expect(missing.ok).toBe(false);
    expect(missing.files[0]?.errors).toContain("Instruction file is missing.");
    expect(valid.ok).toBe(true);
  });
});

async function createRepo(files: Record<string, string>): Promise<string> {
  const repoRoot = await mkdtemp(path.join(tmpdir(), "copilot-instructions-"));

  for (const [relativePath, contents] of Object.entries(files)) {
    const fullPath = path.join(repoRoot, relativePath);
    await mkdir(path.dirname(fullPath), { recursive: true });
    await writeFile(fullPath, contents, "utf8");
  }

  return repoRoot;
}
